kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    targetPort: 80 #pod
    port: 80 #service
  type: NodePort

